wc \
./syncedfs-daemon/config.h \
./syncedfs-daemon/server.c \
./syncedfs-daemon/client.h \
./syncedfs-daemon/server.h \
./syncedfs-daemon/snapshot.h \
./syncedfs-daemon/config.c \
./syncedfs-daemon/snapshot.c \
./syncedfs-daemon/main.c \
./syncedfs-daemon/client.c \
./fstest/fstest.sh \
./syncedfs-common/message_functions.c \
./syncedfs-common/path_functions.c \
./syncedfs-common/logging_functions.h \
./syncedfs-common/path_functions.h \
./syncedfs-common/config_functions.h \
./syncedfs-common/logging_functions.c \
./syncedfs-common/protobuf/syncedfs.proto \
./syncedfs-common/message_functions.h \
./syncedfs-common/config_functions.c \
./fswrite/actions.h \
./fswrite/main.c \
./fswrite/actions.c \
./syncedfs/config.h \
./syncedfs/sighandlers.h \
./syncedfs/syncedfs.c \
./syncedfs/log.c \
./syncedfs/log.h \
./syncedfs/config.c \
./syncedfs/sighandlers.c \
./syncedfs/tests/clean.sh \
./syncedfs/tests/create.sh \
./syncedfs/tests/all.sh \
