/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "syncedfs.pb-c.h"
void   operations_chunk__init
                     (OperationsChunk         *message)
{
  static OperationsChunk init_value = OPERATIONS_CHUNK__INIT;
  *message = init_value;
}
size_t operations_chunk__get_packed_size
                     (const OperationsChunk *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &operations_chunk__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t operations_chunk__pack
                     (const OperationsChunk *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &operations_chunk__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t operations_chunk__pack_to_buffer
                     (const OperationsChunk *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &operations_chunk__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OperationsChunk *
       operations_chunk__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OperationsChunk *)
     protobuf_c_message_unpack (&operations_chunk__descriptor,
                                allocator, len, data);
}
void   operations_chunk__free_unpacked
                     (OperationsChunk *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &operations_chunk__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   file_operation__init
                     (FileOperation         *message)
{
  static FileOperation init_value = FILE_OPERATION__INIT;
  *message = init_value;
}
size_t file_operation__get_packed_size
                     (const FileOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &file_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file_operation__pack
                     (const FileOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &file_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file_operation__pack_to_buffer
                     (const FileOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &file_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FileOperation *
       file_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FileOperation *)
     protobuf_c_message_unpack (&file_operation__descriptor,
                                allocator, len, data);
}
void   file_operation__free_unpacked
                     (FileOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &file_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   generic_operation__init
                     (GenericOperation         *message)
{
  static GenericOperation init_value = GENERIC_OPERATION__INIT;
  *message = init_value;
}
size_t generic_operation__get_packed_size
                     (const GenericOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &generic_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t generic_operation__pack
                     (const GenericOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &generic_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t generic_operation__pack_to_buffer
                     (const GenericOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &generic_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GenericOperation *
       generic_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GenericOperation *)
     protobuf_c_message_unpack (&generic_operation__descriptor,
                                allocator, len, data);
}
void   generic_operation__free_unpacked
                     (GenericOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &generic_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mknod_operation__init
                     (MknodOperation         *message)
{
  static MknodOperation init_value = MKNOD_OPERATION__INIT;
  *message = init_value;
}
size_t mknod_operation__get_packed_size
                     (const MknodOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mknod_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mknod_operation__pack
                     (const MknodOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mknod_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mknod_operation__pack_to_buffer
                     (const MknodOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mknod_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MknodOperation *
       mknod_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MknodOperation *)
     protobuf_c_message_unpack (&mknod_operation__descriptor,
                                allocator, len, data);
}
void   mknod_operation__free_unpacked
                     (MknodOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mknod_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mkdir_operation__init
                     (MkdirOperation         *message)
{
  static MkdirOperation init_value = MKDIR_OPERATION__INIT;
  *message = init_value;
}
size_t mkdir_operation__get_packed_size
                     (const MkdirOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mkdir_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mkdir_operation__pack
                     (const MkdirOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mkdir_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mkdir_operation__pack_to_buffer
                     (const MkdirOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mkdir_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MkdirOperation *
       mkdir_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MkdirOperation *)
     protobuf_c_message_unpack (&mkdir_operation__descriptor,
                                allocator, len, data);
}
void   mkdir_operation__free_unpacked
                     (MkdirOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mkdir_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   symlink_operation__init
                     (SymlinkOperation         *message)
{
  static SymlinkOperation init_value = SYMLINK_OPERATION__INIT;
  *message = init_value;
}
size_t symlink_operation__get_packed_size
                     (const SymlinkOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &symlink_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t symlink_operation__pack
                     (const SymlinkOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &symlink_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t symlink_operation__pack_to_buffer
                     (const SymlinkOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &symlink_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SymlinkOperation *
       symlink_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SymlinkOperation *)
     protobuf_c_message_unpack (&symlink_operation__descriptor,
                                allocator, len, data);
}
void   symlink_operation__free_unpacked
                     (SymlinkOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &symlink_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   unlink_operation__init
                     (UnlinkOperation         *message)
{
  static UnlinkOperation init_value = UNLINK_OPERATION__INIT;
  *message = init_value;
}
size_t unlink_operation__get_packed_size
                     (const UnlinkOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &unlink_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unlink_operation__pack
                     (const UnlinkOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &unlink_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unlink_operation__pack_to_buffer
                     (const UnlinkOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &unlink_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UnlinkOperation *
       unlink_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UnlinkOperation *)
     protobuf_c_message_unpack (&unlink_operation__descriptor,
                                allocator, len, data);
}
void   unlink_operation__free_unpacked
                     (UnlinkOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &unlink_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rmdir_operation__init
                     (RmdirOperation         *message)
{
  static RmdirOperation init_value = RMDIR_OPERATION__INIT;
  *message = init_value;
}
size_t rmdir_operation__get_packed_size
                     (const RmdirOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rmdir_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rmdir_operation__pack
                     (const RmdirOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rmdir_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rmdir_operation__pack_to_buffer
                     (const RmdirOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rmdir_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RmdirOperation *
       rmdir_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RmdirOperation *)
     protobuf_c_message_unpack (&rmdir_operation__descriptor,
                                allocator, len, data);
}
void   rmdir_operation__free_unpacked
                     (RmdirOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rmdir_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rename_operation__init
                     (RenameOperation         *message)
{
  static RenameOperation init_value = RENAME_OPERATION__INIT;
  *message = init_value;
}
size_t rename_operation__get_packed_size
                     (const RenameOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rename_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rename_operation__pack
                     (const RenameOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rename_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rename_operation__pack_to_buffer
                     (const RenameOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rename_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RenameOperation *
       rename_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RenameOperation *)
     protobuf_c_message_unpack (&rename_operation__descriptor,
                                allocator, len, data);
}
void   rename_operation__free_unpacked
                     (RenameOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rename_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   link_operation__init
                     (LinkOperation         *message)
{
  static LinkOperation init_value = LINK_OPERATION__INIT;
  *message = init_value;
}
size_t link_operation__get_packed_size
                     (const LinkOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &link_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t link_operation__pack
                     (const LinkOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &link_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t link_operation__pack_to_buffer
                     (const LinkOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &link_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LinkOperation *
       link_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LinkOperation *)
     protobuf_c_message_unpack (&link_operation__descriptor,
                                allocator, len, data);
}
void   link_operation__free_unpacked
                     (LinkOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &link_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chmod_operation__init
                     (ChmodOperation         *message)
{
  static ChmodOperation init_value = CHMOD_OPERATION__INIT;
  *message = init_value;
}
size_t chmod_operation__get_packed_size
                     (const ChmodOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chmod_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chmod_operation__pack
                     (const ChmodOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chmod_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chmod_operation__pack_to_buffer
                     (const ChmodOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chmod_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChmodOperation *
       chmod_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChmodOperation *)
     protobuf_c_message_unpack (&chmod_operation__descriptor,
                                allocator, len, data);
}
void   chmod_operation__free_unpacked
                     (ChmodOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chmod_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chown_operation__init
                     (ChownOperation         *message)
{
  static ChownOperation init_value = CHOWN_OPERATION__INIT;
  *message = init_value;
}
size_t chown_operation__get_packed_size
                     (const ChownOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chown_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chown_operation__pack
                     (const ChownOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chown_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chown_operation__pack_to_buffer
                     (const ChownOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chown_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChownOperation *
       chown_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChownOperation *)
     protobuf_c_message_unpack (&chown_operation__descriptor,
                                allocator, len, data);
}
void   chown_operation__free_unpacked
                     (ChownOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chown_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   truncate_operation__init
                     (TruncateOperation         *message)
{
  static TruncateOperation init_value = TRUNCATE_OPERATION__INIT;
  *message = init_value;
}
size_t truncate_operation__get_packed_size
                     (const TruncateOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &truncate_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t truncate_operation__pack
                     (const TruncateOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &truncate_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t truncate_operation__pack_to_buffer
                     (const TruncateOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &truncate_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TruncateOperation *
       truncate_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TruncateOperation *)
     protobuf_c_message_unpack (&truncate_operation__descriptor,
                                allocator, len, data);
}
void   truncate_operation__free_unpacked
                     (TruncateOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &truncate_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   write_operation__init
                     (WriteOperation         *message)
{
  static WriteOperation init_value = WRITE_OPERATION__INIT;
  *message = init_value;
}
size_t write_operation__get_packed_size
                     (const WriteOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &write_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t write_operation__pack
                     (const WriteOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &write_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t write_operation__pack_to_buffer
                     (const WriteOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &write_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WriteOperation *
       write_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WriteOperation *)
     protobuf_c_message_unpack (&write_operation__descriptor,
                                allocator, len, data);
}
void   write_operation__free_unpacked
                     (WriteOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &write_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor operations_chunk__field_descriptors[2] =
{
  {
    "relpath",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(OperationsChunk, relpath),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ops",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(OperationsChunk, n_ops),
    PROTOBUF_C_OFFSETOF(OperationsChunk, ops),
    &generic_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned operations_chunk__field_indices_by_name[] = {
  1,   /* field[1] = ops */
  0,   /* field[0] = relpath */
};
static const ProtobufCIntRange operations_chunk__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor operations_chunk__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OperationsChunk",
  "OperationsChunk",
  "OperationsChunk",
  "",
  sizeof(OperationsChunk),
  2,
  operations_chunk__field_descriptors,
  operations_chunk__field_indices_by_name,
  1,  operations_chunk__number_ranges,
  (ProtobufCMessageInit) operations_chunk__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor file_operation__field_descriptors[2] =
{
  {
    "relpath",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FileOperation, relpath),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "op",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FileOperation, op),
    &generic_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file_operation__field_indices_by_name[] = {
  1,   /* field[1] = op */
  0,   /* field[0] = relpath */
};
static const ProtobufCIntRange file_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor file_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "FileOperation",
  "FileOperation",
  "FileOperation",
  "",
  sizeof(FileOperation),
  2,
  file_operation__field_descriptors,
  file_operation__field_indices_by_name,
  1,  file_operation__number_ranges,
  (ProtobufCMessageInit) file_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue generic_operation__operation_type__enum_values_by_number[11] =
{
  { "MKNOD", "GENERIC_OPERATION__OPERATION_TYPE__MKNOD", 3 },
  { "MKDIR", "GENERIC_OPERATION__OPERATION_TYPE__MKDIR", 4 },
  { "SYMLINK", "GENERIC_OPERATION__OPERATION_TYPE__SYMLINK", 5 },
  { "UNLINK", "GENERIC_OPERATION__OPERATION_TYPE__UNLINK", 6 },
  { "RMDIR", "GENERIC_OPERATION__OPERATION_TYPE__RMDIR", 7 },
  { "RENAME", "GENERIC_OPERATION__OPERATION_TYPE__RENAME", 8 },
  { "LINK", "GENERIC_OPERATION__OPERATION_TYPE__LINK", 9 },
  { "CHMOD", "GENERIC_OPERATION__OPERATION_TYPE__CHMOD", 10 },
  { "CHOWN", "GENERIC_OPERATION__OPERATION_TYPE__CHOWN", 11 },
  { "TRUNCATE", "GENERIC_OPERATION__OPERATION_TYPE__TRUNCATE", 12 },
  { "WRITE", "GENERIC_OPERATION__OPERATION_TYPE__WRITE", 13 },
};
static const ProtobufCIntRange generic_operation__operation_type__value_ranges[] = {
{3, 0},{0, 11}
};
const ProtobufCEnumValueIndex generic_operation__operation_type__enum_values_by_name[11] =
{
  { "CHMOD", 7 },
  { "CHOWN", 8 },
  { "LINK", 6 },
  { "MKDIR", 1 },
  { "MKNOD", 0 },
  { "RENAME", 5 },
  { "RMDIR", 4 },
  { "SYMLINK", 2 },
  { "TRUNCATE", 9 },
  { "UNLINK", 3 },
  { "WRITE", 10 },
};
const ProtobufCEnumDescriptor generic_operation__operation_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "GenericOperation.OperationType",
  "OperationType",
  "GenericOperation__OperationType",
  "",
  11,
  generic_operation__operation_type__enum_values_by_number,
  11,
  generic_operation__operation_type__enum_values_by_name,
  1,
  generic_operation__operation_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor generic_operation__field_descriptors[13] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(GenericOperation, has_id),
    PROTOBUF_C_OFFSETOF(GenericOperation, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(GenericOperation, has_type),
    PROTOBUF_C_OFFSETOF(GenericOperation, type),
    &generic_operation__operation_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mknodop",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, mknodop),
    &mknod_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mkdirop",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, mkdirop),
    &mkdir_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symlinkop",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, symlinkop),
    &symlink_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unlinkop",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, unlinkop),
    &unlink_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rmdirop",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, rmdirop),
    &rmdir_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "renameop",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, renameop),
    &rename_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "linkop",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, linkop),
    &link_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chmodop",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, chmodop),
    &chmod_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chownop",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, chownop),
    &chown_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "truncateop",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, truncateop),
    &truncate_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "writeop",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, writeop),
    &write_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned generic_operation__field_indices_by_name[] = {
  9,   /* field[9] = chmodop */
  10,   /* field[10] = chownop */
  0,   /* field[0] = id */
  8,   /* field[8] = linkop */
  3,   /* field[3] = mkdirop */
  2,   /* field[2] = mknodop */
  7,   /* field[7] = renameop */
  6,   /* field[6] = rmdirop */
  4,   /* field[4] = symlinkop */
  11,   /* field[11] = truncateop */
  1,   /* field[1] = type */
  5,   /* field[5] = unlinkop */
  12,   /* field[12] = writeop */
};
static const ProtobufCIntRange generic_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor generic_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "GenericOperation",
  "GenericOperation",
  "GenericOperation",
  "",
  sizeof(GenericOperation),
  13,
  generic_operation__field_descriptors,
  generic_operation__field_indices_by_name,
  1,  generic_operation__number_ranges,
  (ProtobufCMessageInit) generic_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mknod_operation__field_descriptors[1] =
{
  {
    "dummy",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(MknodOperation, has_dummy),
    PROTOBUF_C_OFFSETOF(MknodOperation, dummy),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mknod_operation__field_indices_by_name[] = {
  0,   /* field[0] = dummy */
};
static const ProtobufCIntRange mknod_operation__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mknod_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MknodOperation",
  "MknodOperation",
  "MknodOperation",
  "",
  sizeof(MknodOperation),
  1,
  mknod_operation__field_descriptors,
  mknod_operation__field_indices_by_name,
  1,  mknod_operation__number_ranges,
  (ProtobufCMessageInit) mknod_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mkdir_operation__field_descriptors[1] =
{
  {
    "dummy",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(MkdirOperation, has_dummy),
    PROTOBUF_C_OFFSETOF(MkdirOperation, dummy),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mkdir_operation__field_indices_by_name[] = {
  0,   /* field[0] = dummy */
};
static const ProtobufCIntRange mkdir_operation__number_ranges[1 + 1] =
{
  { 4, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mkdir_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MkdirOperation",
  "MkdirOperation",
  "MkdirOperation",
  "",
  sizeof(MkdirOperation),
  1,
  mkdir_operation__field_descriptors,
  mkdir_operation__field_indices_by_name,
  1,  mkdir_operation__number_ranges,
  (ProtobufCMessageInit) mkdir_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor symlink_operation__field_descriptors[1] =
{
  {
    "dummy",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(SymlinkOperation, has_dummy),
    PROTOBUF_C_OFFSETOF(SymlinkOperation, dummy),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned symlink_operation__field_indices_by_name[] = {
  0,   /* field[0] = dummy */
};
static const ProtobufCIntRange symlink_operation__number_ranges[1 + 1] =
{
  { 5, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor symlink_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "SymlinkOperation",
  "SymlinkOperation",
  "SymlinkOperation",
  "",
  sizeof(SymlinkOperation),
  1,
  symlink_operation__field_descriptors,
  symlink_operation__field_indices_by_name,
  1,  symlink_operation__number_ranges,
  (ProtobufCMessageInit) symlink_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor unlink_operation__field_descriptors[1] =
{
  {
    "dummy",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(UnlinkOperation, has_dummy),
    PROTOBUF_C_OFFSETOF(UnlinkOperation, dummy),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned unlink_operation__field_indices_by_name[] = {
  0,   /* field[0] = dummy */
};
static const ProtobufCIntRange unlink_operation__number_ranges[1 + 1] =
{
  { 6, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor unlink_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "UnlinkOperation",
  "UnlinkOperation",
  "UnlinkOperation",
  "",
  sizeof(UnlinkOperation),
  1,
  unlink_operation__field_descriptors,
  unlink_operation__field_indices_by_name,
  1,  unlink_operation__number_ranges,
  (ProtobufCMessageInit) unlink_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rmdir_operation__field_descriptors[1] =
{
  {
    "dummy",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(RmdirOperation, has_dummy),
    PROTOBUF_C_OFFSETOF(RmdirOperation, dummy),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rmdir_operation__field_indices_by_name[] = {
  0,   /* field[0] = dummy */
};
static const ProtobufCIntRange rmdir_operation__number_ranges[1 + 1] =
{
  { 7, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rmdir_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RmdirOperation",
  "RmdirOperation",
  "RmdirOperation",
  "",
  sizeof(RmdirOperation),
  1,
  rmdir_operation__field_descriptors,
  rmdir_operation__field_indices_by_name,
  1,  rmdir_operation__number_ranges,
  (ProtobufCMessageInit) rmdir_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rename_operation__field_descriptors[1] =
{
  {
    "dummy",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(RenameOperation, has_dummy),
    PROTOBUF_C_OFFSETOF(RenameOperation, dummy),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rename_operation__field_indices_by_name[] = {
  0,   /* field[0] = dummy */
};
static const ProtobufCIntRange rename_operation__number_ranges[1 + 1] =
{
  { 8, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rename_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RenameOperation",
  "RenameOperation",
  "RenameOperation",
  "",
  sizeof(RenameOperation),
  1,
  rename_operation__field_descriptors,
  rename_operation__field_indices_by_name,
  1,  rename_operation__number_ranges,
  (ProtobufCMessageInit) rename_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor link_operation__field_descriptors[1] =
{
  {
    "dummy",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(LinkOperation, has_dummy),
    PROTOBUF_C_OFFSETOF(LinkOperation, dummy),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned link_operation__field_indices_by_name[] = {
  0,   /* field[0] = dummy */
};
static const ProtobufCIntRange link_operation__number_ranges[1 + 1] =
{
  { 9, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor link_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "LinkOperation",
  "LinkOperation",
  "LinkOperation",
  "",
  sizeof(LinkOperation),
  1,
  link_operation__field_descriptors,
  link_operation__field_indices_by_name,
  1,  link_operation__number_ranges,
  (ProtobufCMessageInit) link_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chmod_operation__field_descriptors[1] =
{
  {
    "dummy",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(ChmodOperation, has_dummy),
    PROTOBUF_C_OFFSETOF(ChmodOperation, dummy),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chmod_operation__field_indices_by_name[] = {
  0,   /* field[0] = dummy */
};
static const ProtobufCIntRange chmod_operation__number_ranges[1 + 1] =
{
  { 10, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chmod_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ChmodOperation",
  "ChmodOperation",
  "ChmodOperation",
  "",
  sizeof(ChmodOperation),
  1,
  chmod_operation__field_descriptors,
  chmod_operation__field_indices_by_name,
  1,  chmod_operation__number_ranges,
  (ProtobufCMessageInit) chmod_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chown_operation__field_descriptors[1] =
{
  {
    "dummy",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(ChownOperation, has_dummy),
    PROTOBUF_C_OFFSETOF(ChownOperation, dummy),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chown_operation__field_indices_by_name[] = {
  0,   /* field[0] = dummy */
};
static const ProtobufCIntRange chown_operation__number_ranges[1 + 1] =
{
  { 11, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chown_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ChownOperation",
  "ChownOperation",
  "ChownOperation",
  "",
  sizeof(ChownOperation),
  1,
  chown_operation__field_descriptors,
  chown_operation__field_indices_by_name,
  1,  chown_operation__number_ranges,
  (ProtobufCMessageInit) chown_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor truncate_operation__field_descriptors[1] =
{
  {
    "dummy",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(TruncateOperation, has_dummy),
    PROTOBUF_C_OFFSETOF(TruncateOperation, dummy),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned truncate_operation__field_indices_by_name[] = {
  0,   /* field[0] = dummy */
};
static const ProtobufCIntRange truncate_operation__number_ranges[1 + 1] =
{
  { 12, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor truncate_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "TruncateOperation",
  "TruncateOperation",
  "TruncateOperation",
  "",
  sizeof(TruncateOperation),
  1,
  truncate_operation__field_descriptors,
  truncate_operation__field_indices_by_name,
  1,  truncate_operation__number_ranges,
  (ProtobufCMessageInit) truncate_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor write_operation__field_descriptors[3] =
{
  {
    "offset",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteOperation, offset),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteOperation, size),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(WriteOperation, has_data),
    PROTOBUF_C_OFFSETOF(WriteOperation, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_operation__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = offset */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange write_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor write_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "WriteOperation",
  "WriteOperation",
  "WriteOperation",
  "",
  sizeof(WriteOperation),
  3,
  write_operation__field_descriptors,
  write_operation__field_indices_by_name,
  1,  write_operation__number_ranges,
  (ProtobufCMessageInit) write_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
