/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "syncedfs.pb-c.h"
void   sync_initialization__init
                     (SyncInitialization         *message)
{
  static SyncInitialization init_value = SYNC_INITIALIZATION__INIT;
  *message = init_value;
}
size_t sync_initialization__get_packed_size
                     (const SyncInitialization *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sync_initialization__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sync_initialization__pack
                     (const SyncInitialization *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sync_initialization__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sync_initialization__pack_to_buffer
                     (const SyncInitialization *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sync_initialization__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SyncInitialization *
       sync_initialization__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SyncInitialization *)
     protobuf_c_message_unpack (&sync_initialization__descriptor,
                                allocator, len, data);
}
void   sync_initialization__free_unpacked
                     (SyncInitialization *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sync_initialization__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   file_chunk__init
                     (FileChunk         *message)
{
  static FileChunk init_value = FILE_CHUNK__INIT;
  *message = init_value;
}
size_t file_chunk__get_packed_size
                     (const FileChunk *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &file_chunk__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file_chunk__pack
                     (const FileChunk *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &file_chunk__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file_chunk__pack_to_buffer
                     (const FileChunk *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &file_chunk__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FileChunk *
       file_chunk__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FileChunk *)
     protobuf_c_message_unpack (&file_chunk__descriptor,
                                allocator, len, data);
}
void   file_chunk__free_unpacked
                     (FileChunk *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &file_chunk__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   file_operation__init
                     (FileOperation         *message)
{
  static FileOperation init_value = FILE_OPERATION__INIT;
  *message = init_value;
}
size_t file_operation__get_packed_size
                     (const FileOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &file_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t file_operation__pack
                     (const FileOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &file_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t file_operation__pack_to_buffer
                     (const FileOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &file_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FileOperation *
       file_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FileOperation *)
     protobuf_c_message_unpack (&file_operation__descriptor,
                                allocator, len, data);
}
void   file_operation__free_unpacked
                     (FileOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &file_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   generic_operation__init
                     (GenericOperation         *message)
{
  static GenericOperation init_value = GENERIC_OPERATION__INIT;
  *message = init_value;
}
size_t generic_operation__get_packed_size
                     (const GenericOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &generic_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t generic_operation__pack
                     (const GenericOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &generic_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t generic_operation__pack_to_buffer
                     (const GenericOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &generic_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GenericOperation *
       generic_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GenericOperation *)
     protobuf_c_message_unpack (&generic_operation__descriptor,
                                allocator, len, data);
}
void   generic_operation__free_unpacked
                     (GenericOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &generic_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_operation__init
                     (CreateOperation         *message)
{
  static CreateOperation init_value = CREATE_OPERATION__INIT;
  *message = init_value;
}
size_t create_operation__get_packed_size
                     (const CreateOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &create_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_operation__pack
                     (const CreateOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &create_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_operation__pack_to_buffer
                     (const CreateOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &create_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateOperation *
       create_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateOperation *)
     protobuf_c_message_unpack (&create_operation__descriptor,
                                allocator, len, data);
}
void   create_operation__free_unpacked
                     (CreateOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &create_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mknod_operation__init
                     (MknodOperation         *message)
{
  static MknodOperation init_value = MKNOD_OPERATION__INIT;
  *message = init_value;
}
size_t mknod_operation__get_packed_size
                     (const MknodOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mknod_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mknod_operation__pack
                     (const MknodOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mknod_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mknod_operation__pack_to_buffer
                     (const MknodOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mknod_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MknodOperation *
       mknod_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MknodOperation *)
     protobuf_c_message_unpack (&mknod_operation__descriptor,
                                allocator, len, data);
}
void   mknod_operation__free_unpacked
                     (MknodOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mknod_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mkdir_operation__init
                     (MkdirOperation         *message)
{
  static MkdirOperation init_value = MKDIR_OPERATION__INIT;
  *message = init_value;
}
size_t mkdir_operation__get_packed_size
                     (const MkdirOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mkdir_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mkdir_operation__pack
                     (const MkdirOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mkdir_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mkdir_operation__pack_to_buffer
                     (const MkdirOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mkdir_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MkdirOperation *
       mkdir_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MkdirOperation *)
     protobuf_c_message_unpack (&mkdir_operation__descriptor,
                                allocator, len, data);
}
void   mkdir_operation__free_unpacked
                     (MkdirOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mkdir_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   symlink_operation__init
                     (SymlinkOperation         *message)
{
  static SymlinkOperation init_value = SYMLINK_OPERATION__INIT;
  *message = init_value;
}
size_t symlink_operation__get_packed_size
                     (const SymlinkOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &symlink_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t symlink_operation__pack
                     (const SymlinkOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &symlink_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t symlink_operation__pack_to_buffer
                     (const SymlinkOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &symlink_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SymlinkOperation *
       symlink_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SymlinkOperation *)
     protobuf_c_message_unpack (&symlink_operation__descriptor,
                                allocator, len, data);
}
void   symlink_operation__free_unpacked
                     (SymlinkOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &symlink_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   link_operation__init
                     (LinkOperation         *message)
{
  static LinkOperation init_value = LINK_OPERATION__INIT;
  *message = init_value;
}
size_t link_operation__get_packed_size
                     (const LinkOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &link_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t link_operation__pack
                     (const LinkOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &link_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t link_operation__pack_to_buffer
                     (const LinkOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &link_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LinkOperation *
       link_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LinkOperation *)
     protobuf_c_message_unpack (&link_operation__descriptor,
                                allocator, len, data);
}
void   link_operation__free_unpacked
                     (LinkOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &link_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   write_operation__init
                     (WriteOperation         *message)
{
  static WriteOperation init_value = WRITE_OPERATION__INIT;
  *message = init_value;
}
size_t write_operation__get_packed_size
                     (const WriteOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &write_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t write_operation__pack
                     (const WriteOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &write_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t write_operation__pack_to_buffer
                     (const WriteOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &write_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WriteOperation *
       write_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WriteOperation *)
     protobuf_c_message_unpack (&write_operation__descriptor,
                                allocator, len, data);
}
void   write_operation__free_unpacked
                     (WriteOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &write_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   unlink_operation__init
                     (UnlinkOperation         *message)
{
  static UnlinkOperation init_value = UNLINK_OPERATION__INIT;
  *message = init_value;
}
size_t unlink_operation__get_packed_size
                     (const UnlinkOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &unlink_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unlink_operation__pack
                     (const UnlinkOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &unlink_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unlink_operation__pack_to_buffer
                     (const UnlinkOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &unlink_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UnlinkOperation *
       unlink_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UnlinkOperation *)
     protobuf_c_message_unpack (&unlink_operation__descriptor,
                                allocator, len, data);
}
void   unlink_operation__free_unpacked
                     (UnlinkOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &unlink_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rmdir_operation__init
                     (RmdirOperation         *message)
{
  static RmdirOperation init_value = RMDIR_OPERATION__INIT;
  *message = init_value;
}
size_t rmdir_operation__get_packed_size
                     (const RmdirOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rmdir_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rmdir_operation__pack
                     (const RmdirOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rmdir_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rmdir_operation__pack_to_buffer
                     (const RmdirOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rmdir_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RmdirOperation *
       rmdir_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RmdirOperation *)
     protobuf_c_message_unpack (&rmdir_operation__descriptor,
                                allocator, len, data);
}
void   rmdir_operation__free_unpacked
                     (RmdirOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rmdir_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   truncate_operation__init
                     (TruncateOperation         *message)
{
  static TruncateOperation init_value = TRUNCATE_OPERATION__INIT;
  *message = init_value;
}
size_t truncate_operation__get_packed_size
                     (const TruncateOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &truncate_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t truncate_operation__pack
                     (const TruncateOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &truncate_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t truncate_operation__pack_to_buffer
                     (const TruncateOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &truncate_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TruncateOperation *
       truncate_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TruncateOperation *)
     protobuf_c_message_unpack (&truncate_operation__descriptor,
                                allocator, len, data);
}
void   truncate_operation__free_unpacked
                     (TruncateOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &truncate_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chmod_operation__init
                     (ChmodOperation         *message)
{
  static ChmodOperation init_value = CHMOD_OPERATION__INIT;
  *message = init_value;
}
size_t chmod_operation__get_packed_size
                     (const ChmodOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chmod_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chmod_operation__pack
                     (const ChmodOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chmod_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chmod_operation__pack_to_buffer
                     (const ChmodOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chmod_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChmodOperation *
       chmod_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChmodOperation *)
     protobuf_c_message_unpack (&chmod_operation__descriptor,
                                allocator, len, data);
}
void   chmod_operation__free_unpacked
                     (ChmodOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chmod_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chown_operation__init
                     (ChownOperation         *message)
{
  static ChownOperation init_value = CHOWN_OPERATION__INIT;
  *message = init_value;
}
size_t chown_operation__get_packed_size
                     (const ChownOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chown_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chown_operation__pack
                     (const ChownOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chown_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chown_operation__pack_to_buffer
                     (const ChownOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chown_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChownOperation *
       chown_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChownOperation *)
     protobuf_c_message_unpack (&chown_operation__descriptor,
                                allocator, len, data);
}
void   chown_operation__free_unpacked
                     (ChownOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &chown_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rename_operation__init
                     (RenameOperation         *message)
{
  static RenameOperation init_value = RENAME_OPERATION__INIT;
  *message = init_value;
}
size_t rename_operation__get_packed_size
                     (const RenameOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rename_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rename_operation__pack
                     (const RenameOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rename_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rename_operation__pack_to_buffer
                     (const RenameOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rename_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RenameOperation *
       rename_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RenameOperation *)
     protobuf_c_message_unpack (&rename_operation__descriptor,
                                allocator, len, data);
}
void   rename_operation__free_unpacked
                     (RenameOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rename_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   setxattr_operation__init
                     (SetxattrOperation         *message)
{
  static SetxattrOperation init_value = SETXATTR_OPERATION__INIT;
  *message = init_value;
}
size_t setxattr_operation__get_packed_size
                     (const SetxattrOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &setxattr_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t setxattr_operation__pack
                     (const SetxattrOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &setxattr_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t setxattr_operation__pack_to_buffer
                     (const SetxattrOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &setxattr_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetxattrOperation *
       setxattr_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetxattrOperation *)
     protobuf_c_message_unpack (&setxattr_operation__descriptor,
                                allocator, len, data);
}
void   setxattr_operation__free_unpacked
                     (SetxattrOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &setxattr_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   removexattr_operation__init
                     (RemovexattrOperation         *message)
{
  static RemovexattrOperation init_value = REMOVEXATTR_OPERATION__INIT;
  *message = init_value;
}
size_t removexattr_operation__get_packed_size
                     (const RemovexattrOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &removexattr_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t removexattr_operation__pack
                     (const RemovexattrOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &removexattr_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t removexattr_operation__pack_to_buffer
                     (const RemovexattrOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &removexattr_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RemovexattrOperation *
       removexattr_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RemovexattrOperation *)
     protobuf_c_message_unpack (&removexattr_operation__descriptor,
                                allocator, len, data);
}
void   removexattr_operation__free_unpacked
                     (RemovexattrOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &removexattr_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sync_initialization__field_descriptors[3] =
{
  {
    "sync_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SyncInitialization, sync_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resource",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SyncInitialization, resource),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "number_files",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SyncInitialization, number_files),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sync_initialization__field_indices_by_name[] = {
  2,   /* field[2] = number_files */
  1,   /* field[1] = resource */
  0,   /* field[0] = sync_id */
};
static const ProtobufCIntRange sync_initialization__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sync_initialization__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "SyncInitialization",
  "SyncInitialization",
  "SyncInitialization",
  "",
  sizeof(SyncInitialization),
  3,
  sync_initialization__field_descriptors,
  sync_initialization__field_indices_by_name,
  1,  sync_initialization__number_ranges,
  (ProtobufCMessageInit) sync_initialization__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean file_chunk__last_chunk__default_value = 0;
static const ProtobufCFieldDescriptor file_chunk__field_descriptors[3] =
{
  {
    "relative_path",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FileChunk, relative_path),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ops",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(FileChunk, n_ops),
    PROTOBUF_C_OFFSETOF(FileChunk, ops),
    &generic_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_chunk",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FileChunk, last_chunk),
    NULL,
    &file_chunk__last_chunk__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file_chunk__field_indices_by_name[] = {
  2,   /* field[2] = last_chunk */
  1,   /* field[1] = ops */
  0,   /* field[0] = relative_path */
};
static const ProtobufCIntRange file_chunk__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor file_chunk__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "FileChunk",
  "FileChunk",
  "FileChunk",
  "",
  sizeof(FileChunk),
  3,
  file_chunk__field_descriptors,
  file_chunk__field_indices_by_name,
  1,  file_chunk__number_ranges,
  (ProtobufCMessageInit) file_chunk__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor file_operation__field_descriptors[2] =
{
  {
    "relative_path",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FileOperation, relative_path),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "op",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FileOperation, op),
    &generic_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned file_operation__field_indices_by_name[] = {
  1,   /* field[1] = op */
  0,   /* field[0] = relative_path */
};
static const ProtobufCIntRange file_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor file_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "FileOperation",
  "FileOperation",
  "FileOperation",
  "",
  sizeof(FileOperation),
  2,
  file_operation__field_descriptors,
  file_operation__field_indices_by_name,
  1,  file_operation__number_ranges,
  (ProtobufCMessageInit) file_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue generic_operation__operation_type__enum_values_by_number[14] =
{
  { "CREATE", "GENERIC_OPERATION__OPERATION_TYPE__CREATE", 3 },
  { "MKNOD", "GENERIC_OPERATION__OPERATION_TYPE__MKNOD", 4 },
  { "MKDIR", "GENERIC_OPERATION__OPERATION_TYPE__MKDIR", 5 },
  { "SYMLINK", "GENERIC_OPERATION__OPERATION_TYPE__SYMLINK", 6 },
  { "LINK", "GENERIC_OPERATION__OPERATION_TYPE__LINK", 7 },
  { "WRITE", "GENERIC_OPERATION__OPERATION_TYPE__WRITE", 8 },
  { "UNLINK", "GENERIC_OPERATION__OPERATION_TYPE__UNLINK", 9 },
  { "RMDIR", "GENERIC_OPERATION__OPERATION_TYPE__RMDIR", 10 },
  { "TRUNCATE", "GENERIC_OPERATION__OPERATION_TYPE__TRUNCATE", 11 },
  { "CHMOD", "GENERIC_OPERATION__OPERATION_TYPE__CHMOD", 12 },
  { "CHOWN", "GENERIC_OPERATION__OPERATION_TYPE__CHOWN", 13 },
  { "RENAME", "GENERIC_OPERATION__OPERATION_TYPE__RENAME", 14 },
  { "SETXATTR", "GENERIC_OPERATION__OPERATION_TYPE__SETXATTR", 15 },
  { "REMOVEXATTR", "GENERIC_OPERATION__OPERATION_TYPE__REMOVEXATTR", 16 },
};
static const ProtobufCIntRange generic_operation__operation_type__value_ranges[] = {
{3, 0},{0, 14}
};
const ProtobufCEnumValueIndex generic_operation__operation_type__enum_values_by_name[14] =
{
  { "CHMOD", 9 },
  { "CHOWN", 10 },
  { "CREATE", 0 },
  { "LINK", 4 },
  { "MKDIR", 2 },
  { "MKNOD", 1 },
  { "REMOVEXATTR", 13 },
  { "RENAME", 11 },
  { "RMDIR", 7 },
  { "SETXATTR", 12 },
  { "SYMLINK", 3 },
  { "TRUNCATE", 8 },
  { "UNLINK", 6 },
  { "WRITE", 5 },
};
const ProtobufCEnumDescriptor generic_operation__operation_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "GenericOperation.OperationType",
  "OperationType",
  "GenericOperation__OperationType",
  "",
  14,
  generic_operation__operation_type__enum_values_by_number,
  14,
  generic_operation__operation_type__enum_values_by_name,
  1,
  generic_operation__operation_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor generic_operation__field_descriptors[16] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(GenericOperation, has_id),
    PROTOBUF_C_OFFSETOF(GenericOperation, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, type),
    &generic_operation__operation_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_op",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, create_op),
    &create_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mknod_op",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, mknod_op),
    &mknod_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mkdir_op",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, mkdir_op),
    &mkdir_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symlink_op",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, symlink_op),
    &symlink_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "link_op",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, link_op),
    &link_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "write_op",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, write_op),
    &write_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unlink_op",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, unlink_op),
    &unlink_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rmdir_op",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, rmdir_op),
    &rmdir_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "truncate_op",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, truncate_op),
    &truncate_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chmod_op",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, chmod_op),
    &chmod_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chown_op",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, chown_op),
    &chown_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rename_op",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, rename_op),
    &rename_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "setxattr_op",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, setxattr_op),
    &setxattr_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "removexattr_op",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GenericOperation, removexattr_op),
    &removexattr_operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned generic_operation__field_indices_by_name[] = {
  11,   /* field[11] = chmod_op */
  12,   /* field[12] = chown_op */
  2,   /* field[2] = create_op */
  0,   /* field[0] = id */
  6,   /* field[6] = link_op */
  4,   /* field[4] = mkdir_op */
  3,   /* field[3] = mknod_op */
  15,   /* field[15] = removexattr_op */
  13,   /* field[13] = rename_op */
  9,   /* field[9] = rmdir_op */
  14,   /* field[14] = setxattr_op */
  5,   /* field[5] = symlink_op */
  10,   /* field[10] = truncate_op */
  1,   /* field[1] = type */
  8,   /* field[8] = unlink_op */
  7,   /* field[7] = write_op */
};
static const ProtobufCIntRange generic_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor generic_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "GenericOperation",
  "GenericOperation",
  "GenericOperation",
  "",
  sizeof(GenericOperation),
  16,
  generic_operation__field_descriptors,
  generic_operation__field_indices_by_name,
  1,  generic_operation__number_ranges,
  (ProtobufCMessageInit) generic_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor create_operation__field_descriptors[1] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CreateOperation, mode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_operation__field_indices_by_name[] = {
  0,   /* field[0] = mode */
};
static const ProtobufCIntRange create_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor create_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "CreateOperation",
  "CreateOperation",
  "CreateOperation",
  "",
  sizeof(CreateOperation),
  1,
  create_operation__field_descriptors,
  create_operation__field_indices_by_name,
  1,  create_operation__number_ranges,
  (ProtobufCMessageInit) create_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mknod_operation__field_descriptors[2] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MknodOperation, mode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dev",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MknodOperation, dev),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mknod_operation__field_indices_by_name[] = {
  1,   /* field[1] = dev */
  0,   /* field[0] = mode */
};
static const ProtobufCIntRange mknod_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mknod_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MknodOperation",
  "MknodOperation",
  "MknodOperation",
  "",
  sizeof(MknodOperation),
  2,
  mknod_operation__field_descriptors,
  mknod_operation__field_indices_by_name,
  1,  mknod_operation__number_ranges,
  (ProtobufCMessageInit) mknod_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mkdir_operation__field_descriptors[1] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MkdirOperation, mode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mkdir_operation__field_indices_by_name[] = {
  0,   /* field[0] = mode */
};
static const ProtobufCIntRange mkdir_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mkdir_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MkdirOperation",
  "MkdirOperation",
  "MkdirOperation",
  "",
  sizeof(MkdirOperation),
  1,
  mkdir_operation__field_descriptors,
  mkdir_operation__field_indices_by_name,
  1,  mkdir_operation__number_ranges,
  (ProtobufCMessageInit) mkdir_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor symlink_operation__field_descriptors[1] =
{
  {
    "target",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SymlinkOperation, target),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned symlink_operation__field_indices_by_name[] = {
  0,   /* field[0] = target */
};
static const ProtobufCIntRange symlink_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor symlink_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "SymlinkOperation",
  "SymlinkOperation",
  "SymlinkOperation",
  "",
  sizeof(SymlinkOperation),
  1,
  symlink_operation__field_descriptors,
  symlink_operation__field_indices_by_name,
  1,  symlink_operation__number_ranges,
  (ProtobufCMessageInit) symlink_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor link_operation__field_descriptors[1] =
{
  {
    "newpath",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LinkOperation, newpath),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned link_operation__field_indices_by_name[] = {
  0,   /* field[0] = newpath */
};
static const ProtobufCIntRange link_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor link_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "LinkOperation",
  "LinkOperation",
  "LinkOperation",
  "",
  sizeof(LinkOperation),
  1,
  link_operation__field_descriptors,
  link_operation__field_indices_by_name,
  1,  link_operation__number_ranges,
  (ProtobufCMessageInit) link_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor write_operation__field_descriptors[3] =
{
  {
    "offset",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteOperation, offset),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteOperation, size),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(WriteOperation, has_data),
    PROTOBUF_C_OFFSETOF(WriteOperation, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_operation__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = offset */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange write_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor write_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "WriteOperation",
  "WriteOperation",
  "WriteOperation",
  "",
  sizeof(WriteOperation),
  3,
  write_operation__field_descriptors,
  write_operation__field_indices_by_name,
  1,  write_operation__number_ranges,
  (ProtobufCMessageInit) write_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define unlink_operation__field_descriptors NULL
#define unlink_operation__field_indices_by_name NULL
#define unlink_operation__number_ranges NULL
const ProtobufCMessageDescriptor unlink_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "UnlinkOperation",
  "UnlinkOperation",
  "UnlinkOperation",
  "",
  sizeof(UnlinkOperation),
  0,
  unlink_operation__field_descriptors,
  unlink_operation__field_indices_by_name,
  0,  unlink_operation__number_ranges,
  (ProtobufCMessageInit) unlink_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define rmdir_operation__field_descriptors NULL
#define rmdir_operation__field_indices_by_name NULL
#define rmdir_operation__number_ranges NULL
const ProtobufCMessageDescriptor rmdir_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RmdirOperation",
  "RmdirOperation",
  "RmdirOperation",
  "",
  sizeof(RmdirOperation),
  0,
  rmdir_operation__field_descriptors,
  rmdir_operation__field_indices_by_name,
  0,  rmdir_operation__number_ranges,
  (ProtobufCMessageInit) rmdir_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor truncate_operation__field_descriptors[1] =
{
  {
    "newsize",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TruncateOperation, newsize),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned truncate_operation__field_indices_by_name[] = {
  0,   /* field[0] = newsize */
};
static const ProtobufCIntRange truncate_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor truncate_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "TruncateOperation",
  "TruncateOperation",
  "TruncateOperation",
  "",
  sizeof(TruncateOperation),
  1,
  truncate_operation__field_descriptors,
  truncate_operation__field_indices_by_name,
  1,  truncate_operation__number_ranges,
  (ProtobufCMessageInit) truncate_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chmod_operation__field_descriptors[1] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ChmodOperation, mode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chmod_operation__field_indices_by_name[] = {
  0,   /* field[0] = mode */
};
static const ProtobufCIntRange chmod_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor chmod_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ChmodOperation",
  "ChmodOperation",
  "ChmodOperation",
  "",
  sizeof(ChmodOperation),
  1,
  chmod_operation__field_descriptors,
  chmod_operation__field_indices_by_name,
  1,  chmod_operation__number_ranges,
  (ProtobufCMessageInit) chmod_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chown_operation__field_descriptors[2] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ChownOperation, uid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ChownOperation, gid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chown_operation__field_indices_by_name[] = {
  1,   /* field[1] = gid */
  0,   /* field[0] = uid */
};
static const ProtobufCIntRange chown_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor chown_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ChownOperation",
  "ChownOperation",
  "ChownOperation",
  "",
  sizeof(ChownOperation),
  2,
  chown_operation__field_descriptors,
  chown_operation__field_indices_by_name,
  1,  chown_operation__number_ranges,
  (ProtobufCMessageInit) chown_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rename_operation__field_descriptors[1] =
{
  {
    "newpath",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RenameOperation, newpath),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rename_operation__field_indices_by_name[] = {
  0,   /* field[0] = newpath */
};
static const ProtobufCIntRange rename_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rename_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RenameOperation",
  "RenameOperation",
  "RenameOperation",
  "",
  sizeof(RenameOperation),
  1,
  rename_operation__field_descriptors,
  rename_operation__field_indices_by_name,
  1,  rename_operation__number_ranges,
  (ProtobufCMessageInit) rename_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor setxattr_operation__field_descriptors[1] =
{
  {
    "dummy",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(SetxattrOperation, has_dummy),
    PROTOBUF_C_OFFSETOF(SetxattrOperation, dummy),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned setxattr_operation__field_indices_by_name[] = {
  0,   /* field[0] = dummy */
};
static const ProtobufCIntRange setxattr_operation__number_ranges[1 + 1] =
{
  { 16, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor setxattr_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "SetxattrOperation",
  "SetxattrOperation",
  "SetxattrOperation",
  "",
  sizeof(SetxattrOperation),
  1,
  setxattr_operation__field_descriptors,
  setxattr_operation__field_indices_by_name,
  1,  setxattr_operation__number_ranges,
  (ProtobufCMessageInit) setxattr_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor removexattr_operation__field_descriptors[1] =
{
  {
    "dummy",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(RemovexattrOperation, has_dummy),
    PROTOBUF_C_OFFSETOF(RemovexattrOperation, dummy),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned removexattr_operation__field_indices_by_name[] = {
  0,   /* field[0] = dummy */
};
static const ProtobufCIntRange removexattr_operation__number_ranges[1 + 1] =
{
  { 17, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor removexattr_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RemovexattrOperation",
  "RemovexattrOperation",
  "RemovexattrOperation",
  "",
  sizeof(RemovexattrOperation),
  1,
  removexattr_operation__field_descriptors,
  removexattr_operation__field_indices_by_name,
  1,  removexattr_operation__number_ranges,
  (ProtobufCMessageInit) removexattr_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
